spring.application.name=userManagement

spring.datasource.url=jdbc:mysql://avnadmin:{DB_password}@mysql-1271b86f-mudit-cea1.d.aivencloud.com:11306/defaultdb?ssl-mode=REQUIRED
spring.datasource.username=avnadmin
spring.datasource.password={DB_password}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
